version: 2
image_name: starter
apis:
- agents
- datasetio
- eval
- files
- inference
- safety
- scoring
- telemetry
- tool_runtime
- vector_io
providers:
  inference:
  - provider_id: gemini
    provider_type: remote::gemini
    config:
      api_key: ${env.GEMINI_API_KEY:=}
  - provider_id: vllm
    provider_type: remote::vllm
    config:
      url: ${env.VLLM_URL:=}
      api_token: ${env.VLLM_API_TOKEN:=}
      tls_verify: ${env.VLLM_TLS_VERIFY:=true}
      refresh_models: ${env.VLLM_REFRESH_MODELS:=false}
  vector_io:
  - provider_id: faiss
    provider_type: inline::faiss
    config:
      kvstore:
        type: sqlite
        db_path: ${env.SQLITE_STORE_DIR:=/tmp/.llama/distributions/starter}/faiss_store.db
        namespace: null
  files:
  - provider_id: meta-reference-files
    provider_type: inline::localfs
    config:
      storage_dir: ${env.FILES_STORAGE_DIR:=~/.llama/distributions/starter/files}
      metadata_store:
        type: sqlite
        db_path: ${env.SQLITE_STORE_DIR:=~/.llama/distributions/starter}/files_metadata.db
  safety: []
  agents:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      persistence_store:
        type: postgres
        host: ${env.POSTGRES_HOST:=localhost}
        port: ${env.POSTGRES_PORT:=5432}
        db: ${env.POSTGRES_DB:=assisted-chat}
        user: ${env.POSTGRES_USER:=assisted-chat}
        password: ${env.POSTGRES_PASSWORD:=assisted-chat}
      responses_store:
        type: postgres
        host: ${env.POSTGRES_HOST:=localhost}
        port: ${env.POSTGRES_PORT:=5432}
        db: ${env.POSTGRES_DB:=assisted-chat}
        user: ${env.POSTGRES_USER:=assisted-chat}
        password: ${env.POSTGRES_PASSWORD:=assisted-chat}
  telemetry:
  - provider_id: meta-reference
    provider_type: inline::meta-reference
    config:
      service_name: "${env.OTEL_SERVICE_NAME:=\u200B}"
      sinks: ${env.TELEMETRY_SINKS:=console,sqlite}
      sqlite_db_path: ${env.SQLITE_STORE_DIR:=/tmp/.llama/distributions/starter}/trace_store.db
  eval: []
  datasetio: []
  scoring:
  - provider_id: basic
    provider_type: inline::basic
    config: {}
  - provider_id: llm-as-judge
    provider_type: inline::llm-as-judge
    config: {}
  tool_runtime:
  - provider_id: rag-runtime
    provider_type: inline::rag-runtime
    config: {}
  - provider_id: model-context-protocol
    provider_type: remote::model-context-protocol
    config: {}
metadata_store:
  type: sqlite
  db_path: ${env.SQLITE_STORE_DIR:=/tmp/.llama/distributions/starter}/registry.db
inference_store:
  type: postgres
  host: ${env.POSTGRES_HOST:=localhost}
  port: ${env.POSTGRES_PORT:=5432}
  db: ${env.POSTGRES_DB:=assisted-chat}
  user: ${env.POSTGRES_USER:=assisted-chat}
  password: ${env.POSTGRES_PASSWORD:=assisted-chat}
models:
- metadata: {}
  model_id: models/gemini-2.0-flash
  provider_id: gemini
  provider_model_id: models/gemini-2.0-flash
  model_type: llm
- metadata: {}
  model_id: models/gemini-2.5-pro
  provider_id: gemini
  provider_model_id: models/gemini-2.5-pro
  model_type: llm
- metadata: {}
  model_id: models/gemini-2.5-flash
  provider_id: gemini
  provider_model_id: models/gemini-2.5-flash
  model_type: llm
#- metadata: {}
#  model_id: Qwen2.5-VL-7B-Instruct
#  provider_id: vllm
#  provider_model_id: Qwen2.5-VL-7B-Instruct
#  model_type: llm
#- metadata: {}
#  model_id: openai/gpt-oss-20b
#  provider_id: vllm
#  provider_model_id: openai/gpt-oss-20b
- metadata: {}
  model_id: openai/gpt-oss-120b
  provider_id: vllm
  provider_model_id: openai/gpt-oss-120b
  model_type: llm
#- metadata: {}
#  model_id: Qwen/Qwen3-8B
#  provider_id: vllm
#  provider_model_id: Qwen/Qwen3-8B
#  model_type: llm
shields: []
vector_dbs: []
datasets: []
scoring_fns: []
benchmarks: []
tool_groups:
- toolgroup_id: builtin::rag
  provider_id: rag-runtime
- toolgroup_id: mcp::assisted
  provider_id: model-context-protocol
  mcp_endpoint:
    uri: "http://assisted-service-mcp:8000/mcp"
server:
  port: 8321
